version: 2

updates:
  # npm dependencies
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    groups:
      # Group production dependencies for minor/patch updates
      production-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
      # Group development dependencies for minor/patch updates
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "00:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
