name: Bundle Size

on:
  pull_request:
    branches: [main, master]

jobs:
  size:
    name: Check Bundle Size
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Analyze bundle size
        run: |
          echo "## 📦 Bundle Size Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Package | Size | Gzip |" >> $GITHUB_STEP_SUMMARY
          echo "|---------|------|------|" >> $GITHUB_STEP_SUMMARY

          for pkg in packages/*/dist/*.js; do
            if [ -f "$pkg" ]; then
              size=$(du -h "$pkg" | cut -f1)
              gzip_size=$(gzip -c "$pkg" | wc -c | numfmt --to=iec)
              pkg_name=$(basename $(dirname $(dirname "$pkg")))
              file_name=$(basename "$pkg")
              echo "| $pkg_name/$file_name | $size | $gzip_size |" >> $GITHUB_STEP_SUMMARY
            fi
          done

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const summary = fs.readFileSync(process.env.GITHUB_STEP_SUMMARY, 'utf8');

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });
