name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Clean npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm install --prefer-offline --no-audit

    - name: Run tests
      run: npx vitest run